kind: pipeline
type: docker
name: backend

steps:
  - name: backend
    image: node
    commands:
      - node index.js
trigger:
  branch:
    - master
  event:
    - push
---
kind: pipeline
type: docker
name: frontend

steps:
  - name: build
    image: node
    commands:
      - echo "testing"
depends_on:
 - backend
